name: lint
on: [push, pull_request]
jobs:
  check-licences:
    name: Check Licences
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Enable Problem Matcher for GitHub annotations
        run: echo "::add-matcher::.github/problem-matcher-lint-check-licences.json"
      - name: Check licenses
        shell: bash
        run: ./scripts/enforce_licence.py
  generic-nolints:
    name: Count generic NOLINTs
    runs-on: ubuntu-latest
    steps:
      - run: id
      - run: ls -al
      - run: ls -al -n
      - run: ls -al ..
      - run: ls -al -n ..
      - run: ls -al "$GITHUB_WORKSPACE"
      - run: ls -al -n "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v3
      - name: Enable Problem Matcher for GitHub annotations
        run: echo "::add-matcher::.github/problem-matcher-lint-generic-nolints.json"
      - name: Count the number of generic NOLINTs
        shell: bash
        run: ./scripts/count_generic_nolints.sh
  build:
    name: Build for Lint Tasks
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - run: id
      - run: ls -al
      - run: ls -al -n
      - run: ls -al ..
      - run: ls -al -n ..
      - run: ls -al "$GITHUB_WORKSPACE"
      - run: ls -al -n "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v3
      - name: Update package database
        run: apt-get update -y
      - name: Install build tools
        shell: bash
        run: |
          apt-get -y install pkg-config libtool autoconf \
            automake g++ bison flex make bash-completion dh-autoreconf \
            debhelper devscripts wget python3-pip
      - name: Install Python lint tools
        run: python3 -m pip install --no-input cpplint flake8
      - name: Install build dependencies
        shell: bash
        run: |
          apt-get -y install libcppunit-dev uuid-dev libncurses5-dev \
            libmicrohttpd-dev protobuf-compiler python3-protobuf \
            libprotobuf-dev libprotoc-dev zlib1g-dev libftdi-dev \
            libusb-1.0-0-dev liblo-dev libavahi-client-dev python3-numpy
      - name: Autoreconf
        run: autoreconf -i
      - name: Configure
        run: ./configure --enable-rdm-tests --enable-ja-rule --enable-e133
      - name: Build
        run: make builtfiles VERBOSE=1
      - name: Archive artifacts to speed up slow GH Actions upload/download
        shell: bash
        run: |
          touch ola-debian-stable-built-source-tree.tar.gz
          tar --exclude=ola-debian-stable-built-source-tree.tar.gz -cvzf ola-debian-stable-built-source-tree.tar.gz .
      - name: SHA256 artifact archive
        run: sha256sum ola-debian-stable-built-source-tree.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: ola-debian-stable-built-source-tree
          path: ola-debian-stable-built-source-tree.tar.gz
  cpplint:
    name: cpplint
    runs-on: ubuntu-latest
    container:
      image: debian:stable
      options: "-v ${{ github.workspace }}:/__w/ola/ola"
    needs: build
    steps:
      - name: Download built source tree archive
        uses: actions/download-artifact@v3
        with:
          name: ola-debian-stable-built-source-tree
          path: .
      - name: SHA256 artifact archive
        run: sha256sum ola-debian-stable-built-source-tree.tar.gz
      - name: Unarchive artifacts and delete archive
        shell: bash
        run: |
          tar -xvzf ola-debian-stable-built-source-tree.tar.gz .
          rm ola-debian-stable-built-source-tree.tar.gz
      - name: Display structure of extracted files
        run: ls -alR
      - name: Update package database
        run: apt-get update -y
      - name: Install build tools
        shell: bash
        run: |
          apt-get -y install pkg-config libtool autoconf \
            automake g++ bison flex make bash-completion dh-autoreconf \
            debhelper devscripts wget python3-pip
      - name: Install Python lint tools
        run: python3 -m pip install --no-input cpplint flake8
      - name: Install build dependencies
        shell: bash
        run: |
          apt-get -y install libcppunit-dev uuid-dev libncurses5-dev \
            libmicrohttpd-dev protobuf-compiler python3-protobuf \
            libprotobuf-dev libprotoc-dev zlib1g-dev libftdi-dev \
            libusb-1.0-0-dev liblo-dev libavahi-client-dev python3-numpy
      - name: Enable Problem Matcher for GitHub annotations
        run: echo "::add-matcher::.github/problem-matcher-lint-cpplint.json"
      - name: cpplint
        run: make cpplint VERBOSE=1
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    container: debian:stable
    needs: build
    steps:
      - name: Download built source tree archive
        uses: actions/download-artifact@v3
        with:
          name: ola-debian-stable-built-source-tree
          path: .
      - name: SHA256 artifact archive
        run: sha256sum ola-debian-stable-built-source-tree.tar.gz
      - name: Unarchive artifacts and delete archive
        shell: bash
        run: |
          tar -xvzf ola-debian-stable-built-source-tree.tar.gz .
          rm ola-debian-stable-built-source-tree.tar.gz
      - name: Display structure of extracted files
        run: ls -alR
      - name: Update package database
        run: apt-get update -y
      - name: Install build tools
        shell: bash
        run: |
          apt-get -y install pkg-config libtool autoconf \
            automake g++ bison flex make bash-completion dh-autoreconf \
            debhelper devscripts wget python3-pip
      - name: Install Python lint tools
        run: python3 -m pip install --no-input cpplint flake8
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Install build dependencies
        shell: bash
        run: |
          apt-get -y install libcppunit-dev uuid-dev libncurses5-dev \
            libmicrohttpd-dev protobuf-compiler python3-protobuf \
            libprotobuf-dev libprotoc-dev zlib1g-dev libftdi-dev \
            libusb-1.0-0-dev liblo-dev libavahi-client-dev python3-numpy
      - name: flake8
        run: make flake8 VERBOSE=1
